// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AdminUser"
                        }
                    }
                }
            }
        },
        "/admin/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "_page",
                        "name": "_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "_limit",
                        "name": "_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    }
                }
            }
        },
        "/clubs/goldenpearl/about-us": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clubs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GoldenPearlAboutUs"
                        }
                    }
                }
            }
        },
        "/common/country/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Country"
                            }
                        }
                    }
                }
            }
        },
        "/common/nationality/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Nationality"
                            }
                        }
                    }
                }
            }
        },
        "/common/telcode/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.CountryTelCode"
                            }
                        }
                    }
                }
            }
        },
        "/future-order/all/{prn}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Future Order"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "prn",
                        "name": "prn",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "_page",
                        "name": "_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "_limit",
                        "name": "_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.FutureOrder"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notification/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.OneSignalNotification"
                            }
                        }
                    }
                }
            }
        },
        "/notification/general/master/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.GeneralNotification"
                            }
                        }
                    }
                }
            }
        },
        "/notification/general/master/{notificationMasterId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification MasterId",
                        "name": "notificationMasterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GeneralNotification"
                        }
                    }
                }
            }
        },
        "/notification/unseen/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/notification/{notificationId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Id",
                        "name": "notificationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OneSignalNotification"
                        }
                    }
                }
            }
        },
        "/user/add-machine-id": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "AddMachineId Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostMachineInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "_page",
                        "name": "_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "_limit",
                        "name": "_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApplicationUser"
                            }
                        }
                    }
                }
            }
        },
        "/user/all/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "_page",
                        "name": "_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "_limit",
                        "name": "_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApplicationUser"
                            }
                        }
                    }
                }
            }
        },
        "/user/update-playerid/{playerId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "PlayerId",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "fromAdmin": {
                    "type": "boolean",
                    "default": false
                },
                "fromBiometric": {
                    "type": "integer",
                    "default": 0
                },
                "machineId": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "default": "Abcd1234"
                },
                "playerId": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "default": "eugene.lim@nova-hub.com"
                }
            }
        },
        "dto.PostMachineInfo": {
            "type": "object",
            "required": [
                "machineId"
            ],
            "properties": {
                "machineId": {
                    "type": "string"
                }
            }
        },
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "adminBranches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AssignBranch"
                    }
                },
                "admin_id": {
                    "type": "integer"
                },
                "contactNumber": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "passport": {
                    "type": "string"
                },
                "resident": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userGroupId": {
                    "type": "integer"
                },
                "userGroupName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.ApplicationUser": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "address1": {
                    "type": "string"
                },
                "address2": {
                    "type": "string"
                },
                "address3": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "cityState": {
                    "type": "string"
                },
                "contactNumber": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "dateLoggedIn": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "docNoSignUp": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "firstTimeBiometric": {
                    "type": "boolean"
                },
                "firstTimeLogin": {
                    "type": "boolean"
                },
                "fullName": {
                    "type": "string"
                },
                "fullNameSignUp": {
                    "type": "string"
                },
                "inactive": {
                    "type": "string"
                },
                "isGoldenPearl": {
                    "type": "string"
                },
                "isKidsExplorer": {
                    "type": "string"
                },
                "isLoggedIn": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "machineId": {
                    "type": "string"
                },
                "masterPrn": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "passport": {
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "race": {
                    "type": "string"
                },
                "registration_date_time": {
                    "type": "string"
                },
                "resident": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "signInType": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "userBranches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AssignBranch"
                    }
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "verificationCode": {
                    "type": "string"
                }
            }
        },
        "model.AssignBranch": {
            "type": "object",
            "properties": {
                "adminId": {
                    "type": "integer"
                },
                "assignBranchId": {
                    "type": "integer"
                },
                "branch": {
                    "$ref": "#/definitions/model.Branch"
                },
                "branchId": {
                    "type": "integer"
                },
                "prn": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.Branch": {
            "type": "object",
            "properties": {
                "branchId": {
                    "type": "integer"
                },
                "branchName": {
                    "type": "string"
                },
                "passcode": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.Country": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "type": "string"
                },
                "countryName": {
                    "type": "string"
                },
                "telCode": {
                    "type": "string"
                }
            }
        },
        "model.CountryTelCode": {
            "type": "object",
            "properties": {
                "countryName": {
                    "type": "string"
                },
                "telCode": {
                    "type": "string"
                }
            }
        },
        "model.FutureOrder": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "orderDoctor": {
                    "type": "string"
                },
                "patientName": {
                    "type": "string"
                },
                "performDate": {
                    "type": "string"
                },
                "planType": {
                    "type": "string"
                },
                "prn": {
                    "type": "string"
                }
            }
        },
        "model.GeneralNotification": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "fullMessage": {
                    "type": "string"
                },
                "notificationTitle": {
                    "type": "string"
                },
                "notification_master_id": {
                    "type": "integer"
                },
                "shortMessage": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "targetAgeFrom": {
                    "type": "integer"
                },
                "targetAgeTo": {
                    "type": "integer"
                },
                "targetCity": {
                    "type": "string"
                },
                "targetGender": {
                    "type": "string"
                },
                "targetNationality": {
                    "type": "string"
                },
                "targetState": {
                    "type": "string"
                }
            }
        },
        "model.GoldenPearlAboutUs": {
            "type": "object",
            "properties": {
                "goldenClubDesc": {
                    "type": "string"
                },
                "goldenClubExtLink": {
                    "type": "string"
                },
                "goldenClubImage": {
                    "type": "string"
                },
                "goldenClubTitle": {
                    "type": "string"
                },
                "goldenClubTnc": {
                    "type": "string"
                },
                "golden_club_id": {
                    "type": "integer"
                }
            }
        },
        "model.Nationality": {
            "type": "object",
            "properties": {
                "nationality": {
                    "type": "string"
                }
            }
        },
        "model.OneSignalNotification": {
            "type": "object",
            "properties": {
                "accountNo": {
                    "type": "string"
                },
                "dateCreate": {
                    "type": "string"
                },
                "dateSent": {
                    "type": "string"
                },
                "fullMessage": {
                    "type": "string"
                },
                "guestPlayerId": {
                    "type": "string"
                },
                "isSeen": {
                    "type": "boolean"
                },
                "master_id": {
                    "type": "integer"
                },
                "msgType": {
                    "type": "string"
                },
                "notificationTitle": {
                    "type": "string"
                },
                "notification_id": {
                    "type": "integer"
                },
                "shortMessage": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "visitType": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/ih/mobile_central_2_0_0",
	Schemes:          []string{},
	Title:            "(IHP-UAT) Vesalius-m Backend API",
	Description:      "Vesalius-m Backend API Docs (IHP-UAT Version).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
