basePath: /ih/mobile_central_2_0_0
definitions:
  dto.LoginDto:
    properties:
      fromAdmin:
        default: false
        type: boolean
      fromBiometric:
        default: 0
        type: integer
      machineId:
        type: string
      password:
        type: string
      playerId:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.ApplicationUser:
    properties:
      address:
        type: string
      address1:
        type: string
      address2:
        type: string
      address3:
        type: string
      branch:
        type: string
      cityState:
        type: string
      contactNumber:
        type: string
      country:
        type: string
      dateLoggedIn:
        type: string
      dob:
        type: string
      docNoSignUp:
        type: string
      email:
        type: string
      firstName:
        type: string
      firstTimeBiometric:
        type: boolean
      firstTimeLogin:
        type: boolean
      fullName:
        type: string
      fullNameSignUp:
        type: string
      inactive:
        type: string
      isGoldenPearl:
        type: string
      isKidsExplorer:
        type: string
      isLoggedIn:
        type: integer
      lastName:
        type: string
      machineId:
        type: string
      masterPrn:
        type: string
      middleName:
        type: string
      nationality:
        type: string
      passport:
        type: string
      playerId:
        type: string
      postalCode:
        type: string
      race:
        type: string
      registration_date_time:
        type: string
      resident:
        type: string
      role:
        type: string
      sessionId:
        type: string
      sex:
        type: string
      signInType:
        type: integer
      title:
        type: string
      user_id:
        type: integer
      userBranches:
        items:
          $ref: '#/definitions/model.AssignBranch'
        type: array
      username:
        type: string
      verificationCode:
        type: string
    type: object
  model.AssignBranch:
    properties:
      adminId:
        type: integer
      assignBranchId:
        type: integer
      branch:
        $ref: '#/definitions/model.Branch'
      branchId:
        type: integer
      prn:
        type: string
      userId:
        type: integer
    type: object
  model.Branch:
    properties:
      branchId:
        type: integer
      branchName:
        type: string
      passcode:
        type: string
      url:
        type: string
    type: object
  model.Country:
    properties:
      countryCode:
        type: string
      countryName:
        type: string
      telCode:
        type: string
    type: object
  model.CountryTelCode:
    properties:
      countryName:
        type: string
      telCode:
        type: string
    type: object
  model.Nationality:
    properties:
      nationality:
        type: string
    type: object
info:
  contact: {}
  description: Vesalius-m Backend API Docs (IHP-UAT Version).
  title: (IHP-UAT) Vesalius-m Backend API
  version: "1.0"
paths:
  /common/country/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Country'
            type: array
      tags:
      - Common
  /common/nationality/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Nationality'
            type: array
      tags:
      - Common
  /common/telcode/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.CountryTelCode'
            type: array
      tags:
      - Common
  /login:
    post:
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - Auth
  /user/all:
    get:
      parameters:
      - description: _page
        in: query
        name: _page
        type: string
      - description: _limit
        in: query
        name: _limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ApplicationUser'
            type: array
      security:
      - BearerAuth: []
      tags:
      - User
  /user/all/active:
    get:
      parameters:
      - description: _page
        in: query
        name: _page
        type: string
      - description: _limit
        in: query
        name: _limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ApplicationUser'
            type: array
      security:
      - BearerAuth: []
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
